linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - misspell
    - revive

run:
  timeout: 5m
  tests: false

issues:
  exclude-use-default: false